import eslintPluginImport from 'eslint-plugin-import';
import tsEslintPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';

export default [
  {
    files: ['**/*.js'],
    ignores: [
      'node_modules/**',
      'dist/**',
      'tests/**',
      '.vite/**'
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        module: 'readonly',
        require: 'readonly',
        process: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        FileReader: 'readonly',
        Blob: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        BroadcastChannel: 'readonly',
        crypto: 'readonly',
        caches: 'readonly',
        sessionStorage: 'readonly',
        localStorage: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        history: 'readonly',
        location: 'readonly',
        navigator: 'readonly',
        performance: 'readonly',
        CSS: 'readonly',
        ClipboardItem: 'readonly',
        HTMLElement: 'readonly',
        getComputedStyle: 'readonly',
        NodeFilter: 'readonly',
        queueMicrotask: 'readonly',
        Node: 'readonly',
        TextEncoder: 'readonly',
        btoa: 'readonly',
        WebSocket: 'readonly',
        alert: 'readonly',
      },
    },
    plugins: {
      import: eslintPluginImport,
    },
    rules: {
      'no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        caughtErrors: 'none'
      }],
      'no-undef': 'error',
      'no-debugger': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-empty': ['error', { allowEmptyCatch: false }],
      'no-var': 'error',
      'prefer-const': 'warn',
      'eqeqeq': 'warn',
      'import/no-unresolved': 'off',
    },
  },
  {
    files: ['**/*.ts'],
    ignores: [
      'node_modules/**',
      'dist/**',
      'tests/**',
      '.vite/**'
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parser: tsParser,
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        module: 'readonly',
        require: 'readonly',
        process: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        FileReader: 'readonly',
        Blob: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        BroadcastChannel: 'readonly',
        crypto: 'readonly',
        caches: 'readonly',
        sessionStorage: 'readonly',
        localStorage: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        history: 'readonly',
        location: 'readonly',
        navigator: 'readonly',
        performance: 'readonly',
        CSS: 'readonly',
        ClipboardItem: 'readonly',
        HTMLElement: 'readonly',
        getComputedStyle: 'readonly',
        NodeFilter: 'readonly',
        queueMicrotask: 'readonly',
        Node: 'readonly',
        TextEncoder: 'readonly',
        btoa: 'readonly',
        WebSocket: 'readonly',
        alert: 'readonly',
      },
    },
    plugins: {
      import: eslintPluginImport,
      '@typescript-eslint': tsEslintPlugin,
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        caughtErrors: 'none'
      }],
      'no-undef': 'off',
      'no-debugger': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-empty': ['error', { allowEmptyCatch: false }],
      'no-var': 'error',
      'prefer-const': 'warn',
      'eqeqeq': 'warn',
      'import/no-unresolved': 'off',
      'no-unused-vars': 'off',
    },
  },
  {
    files: ['js/utils/console_manager.js'],
    rules: {
      'no-console': 'off',
    },
  },
];
