export default {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/tests/setup-jest.js'],
  moduleNameMapper: {
    '\\.(css)$': '<rootDir>/tests/styleMock.js',
    // Migrerade moduler: import behåller .js (Vite/TS) men filen heter .ts — Jest behöver explicit mappning.
    '^.+/audit_logic\\.js$': '<rootDir>/js/audit_logic.ts',
    '^.+/audit_logic_types\\.js$': '<rootDir>/js/logic/audit_logic_types.ts',
    '^.+/audit_logic_i18n\\.js$': '<rootDir>/js/logic/audit_logic_i18n.ts',
    '^.+/audit_logic_lookup\\.js$': '<rootDir>/js/logic/audit_logic_lookup.ts',
    '^.+/audit_logic_status\\.js$': '<rootDir>/js/logic/audit_logic_status.ts',
    '^.+/audit_logic_deficiency\\.js$': '<rootDir>/js/logic/audit_logic_deficiency.ts',
    '^.+/audit_logic_requirements_lists\\.js$': '<rootDir>/js/logic/audit_logic_requirements_lists.ts',
    '^.+/audit_logic_progress\\.js$': '<rootDir>/js/logic/audit_logic_progress.ts',
    '^.+/audit_logic_recalc\\.js$': '<rootDir>/js/logic/audit_logic_recalc.ts',
    '^.+/audit_logic_problems_media\\.js$': '<rootDir>/js/logic/audit_logic_problems_media.ts',
    '^.+/export_logic\\.js$': '<rootDir>/js/export_logic.ts',
    '^.+[\\\\/]export_format_helpers\\.js$': '<rootDir>/js/export/export_format_helpers.ts',
    '^.+[\\\\/]export_bootstrap\\.js$': '<rootDir>/js/export/export_bootstrap.ts',
    '^.+[\\\\/]export_csv\\.js$': '<rootDir>/js/export/export_csv.ts',
    '^.+[\\\\/]export_deficiency_traversal\\.js$': '<rootDir>/js/export/export_deficiency_traversal.ts',
    '^.+[\\\\/]export_excel\\.js$': '<rootDir>/js/export/export_excel.ts',
    '^.+[\\\\/]export_word_markdown_docx\\.js$': '<rootDir>/js/export/export_word_markdown_docx.ts',
    '^.+[\\\\/]export_word_requirement_sections\\.js$': '<rootDir>/js/export/export_word_requirement_sections.ts',
    '^.+[\\\\/]export_word_deficiency_queries\\.js$': '<rootDir>/js/export/export_word_deficiency_queries.ts',
    '^.+[\\\\/]export_word_detail_pages\\.js$': '<rootDir>/js/export/export_word_detail_pages.ts',
    '^.+[\\\\/]export_word_main_flow\\.js$': '<rootDir>/js/export/export_word_main_flow.ts',
    '^.+[\\\\/]export_word_deprecated_text_export\\.js$': '<rootDir>/js/export/export_word_deprecated_text_export.ts',
    '^.+[\\\\/]export_html_build\\.js$': '<rootDir>/js/export/export_html_build.ts',
    '^.+[\\\\/]export_html_audit_hash\\.js$': '<rootDir>/js/export/export_html_audit_hash.ts',
    '^.+[\\\\/]export_html_styles_generated\\.js$': '<rootDir>/js/export/export_html_styles_generated.ts',
    '^.+[\\\\/]export_html_script_generated\\.js$': '<rootDir>/js/export/export_html_script_generated.ts',
    '^.+[\\\\/]export_html_export\\.js$': '<rootDir>/js/export/export_html_export.ts',
    '^.+/auditReducer\\.js$': '<rootDir>/js/state/auditReducer.ts',
    '^.+/audit_reducer_time\\.js$': '<rootDir>/js/state/audit_reducer_time.ts',
    '^.+/auditResultAliases\\.js$': '<rootDir>/js/state/auditResultAliases.ts',
    '^.+/metadataHandlers\\.js$': '<rootDir>/js/state/metadataHandlers.ts',
    '^.+/auditStatusHandlers\\.js$': '<rootDir>/js/state/auditStatusHandlers.ts',
    '^.+/sampleHandlers\\.js$': '<rootDir>/js/state/sampleHandlers.ts',
    '^.+/remoteStateHandlers\\.js$': '<rootDir>/js/state/remoteStateHandlers.ts',
    '^.+/same_user_tab_field_sync\\.js$': '<rootDir>/js/logic/same_user_tab_field_sync.ts',
    '^.+/RequirementAuditComponent\\.js$': '<rootDir>/js/components/RequirementAuditComponent.ts',
    '^.+/RequirementAuditSidebarComponent\\.js$': '<rootDir>/js/components/RequirementAuditSidebarComponent.ts',
    '^.+/AuditActionsViewComponent\\.js$': '<rootDir>/js/components/AuditActionsViewComponent.ts',
    '^.+/AuditProblemsViewComponent\\.js$': '<rootDir>/js/components/AuditProblemsViewComponent.ts',
    '^.+/ConfirmUpdatesViewComponent\\.js$': '<rootDir>/js/components/ConfirmUpdatesViewComponent.ts',
    '^.+/FinalConfirmUpdatesViewComponent\\.js$': '<rootDir>/js/components/FinalConfirmUpdatesViewComponent.ts',
    '^.+/SampleListComponent\\.js$': '<rootDir>/js/components/SampleListComponent.ts',
    '^.+/requirement_list_query\\.js$': '<rootDir>/js/components/requirements_list/requirement_list_query.ts',
    '^.+/requirement_list_filter_requirements\\.js$':
      '<rootDir>/js/components/requirements_list/requirement_list_filter_requirements.ts',
    '^.+/requirement_list_incremental_dom\\.js$':
      '<rootDir>/js/components/requirements_list/requirement_list_incremental_dom.ts',
    '^.+/requirement_list_list_items\\.js$': '<rootDir>/js/components/requirements_list/requirement_list_list_items.ts',
    '^.+/requirement_list_mark_all_modal\\.js$':
      '<rootDir>/js/components/requirements_list/requirement_list_mark_all_modal.ts',
    '^.+/requirement_search_utils\\.js$': '<rootDir>/js/utils/requirement_search_utils.ts',
    '^.+/string_filter_normalize\\.js$': '<rootDir>/js/utils/string_filter_normalize.ts',
    '^.+/traverse_audit_data\\.js$': '<rootDir>/js/utils/traverse_audit_data.ts',
  },
  testMatch: [
    '<rootDir>/tests/unit/**/*.spec.js',
    '<rootDir>/tests/unit/**/*.spec.ts',
  ],
  testPathIgnorePatterns: ['/node_modules/', '.e2e.spec.js'],
  /** Tillåt transpilering av marked (ESM) så js/utils/markdown.js kan laddas i Jest. */
  transformIgnorePatterns: ['/node_modules/(?!(marked)/)'],
  transform: {
    '^.+\\.(t|j)s$': [
      '@swc/jest',
      {
        jsc: {
          parser: {
            syntax: 'typescript',
          },
          target: 'es2022',
        },
        module: {
          type: 'es6',
        },
      },
    ],
  },
  extensionsToTreatAsEsm: ['.ts'],
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  collectCoverageFrom: [
    'js/logic/**/*.{js,ts}',
    'js/api/**/*.{js,ts}',
    'js/state/**/*.{js,ts}',
    '!js/**/*.spec.{js,ts}',
  ],
};
