export default {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/tests/setup-jest.js'],
  moduleNameMapper: {
    '\\.(css)$': '<rootDir>/tests/styleMock.js',
    // Migrerade moduler: import behåller .js (Vite/TS) men filen heter .ts — Jest behöver explicit mappning.
    '^.+/audit_logic\\.js$': '<rootDir>/js/audit_logic.ts',
    '^.+/audit_logic_types\\.js$': '<rootDir>/js/logic/audit_logic_types.ts',
    '^.+/audit_logic_i18n\\.js$': '<rootDir>/js/logic/audit_logic_i18n.ts',
    '^.+/audit_logic_lookup\\.js$': '<rootDir>/js/logic/audit_logic_lookup.ts',
    '^.+/audit_logic_status\\.js$': '<rootDir>/js/logic/audit_logic_status.ts',
    '^.+[\\\\/]entity_id_match\\.js$': '<rootDir>/js/logic/entity_id_match.ts',
    '^.+/audit_logic_deficiency\\.js$': '<rootDir>/js/logic/audit_logic_deficiency.ts',
    '^.+/audit_logic_requirements_lists\\.js$': '<rootDir>/js/logic/audit_logic_requirements_lists.ts',
    '^.+/audit_logic_progress\\.js$': '<rootDir>/js/logic/audit_logic_progress.ts',
    '^.+/audit_logic_recalc\\.js$': '<rootDir>/js/logic/audit_logic_recalc.ts',
    '^.+/audit_list_last_updated\\.js$': '<rootDir>/js/logic/audit_list_last_updated.ts',
    '^.+/audit_list_progress\\.js$': '<rootDir>/js/logic/audit_list_progress.ts',
    '^.+/closed_audit_assessment_gap_fill\\.js$': '<rootDir>/js/logic/closed_audit_assessment_gap_fill.ts',
    '^.+/requirement_assessment_gap_fill\\.js$': '<rootDir>/js/logic/requirement_assessment_gap_fill.ts',
    '^.+/audit_logic_problems_media\\.js$': '<rootDir>/js/logic/audit_logic_problems_media.ts',
    '^.+/ScoreCalculator\\.js$': '<rootDir>/js/logic/ScoreCalculator.ts',
    '^.+/score_calculator_passed_check_failures\\.js$': '<rootDir>/js/logic/score_calculator_passed_check_failures.ts',
    '^.+/export_logic\\.js$': '<rootDir>/js/export_logic.ts',
    '^.+[\\\\/]export_format_helpers\\.js$': '<rootDir>/js/export/export_format_helpers.ts',
    '^.+[\\\\/]deficiency_id_display\\.js$': '<rootDir>/js/utils/deficiency_id_display.ts',
    '^.+[\\\\/]export_bootstrap\\.js$': '<rootDir>/js/export/export_bootstrap.ts',
    '^.+[\\\\/]export_csv\\.js$': '<rootDir>/js/export/export_csv.ts',
    '^.+[\\\\/]export_deficiency_rows\\.js$': '<rootDir>/js/export/export_deficiency_rows.ts',
    '^.+[\\\\/]export_deficiency_traversal\\.js$': '<rootDir>/js/export/export_deficiency_traversal.ts',
    '^.+[\\\\/]export_excel\\.js$': '<rootDir>/js/export/export_excel.ts',
    '^.+[\\\\/]excel_export_helpers\\.js$': '<rootDir>/js/export/excel_export_helpers.ts',
    '^.+[\\\\/]excel_deficiencies_sheet\\.js$': '<rootDir>/js/export/excel_deficiencies_sheet.ts',
    '^.+[\\\\/]export_word_markdown_docx\\.js$': '<rootDir>/js/export/export_word_markdown_docx.ts',
    '^.+[\\\\/]export_word_requirement_sections\\.js$': '<rootDir>/js/export/export_word_requirement_sections.ts',
    '^.+[\\\\/]export_word_deficiency_queries\\.js$': '<rootDir>/js/export/export_word_deficiency_queries.ts',
    '^.+[\\\\/]export_word_detail_pages\\.js$': '<rootDir>/js/export/export_word_detail_pages.ts',
    '^.+[\\\\/]export_word_main_flow\\.js$': '<rootDir>/js/export/export_word_main_flow.ts',
    '^.+[\\\\/]export_word_main_flow_children\\.js$': '<rootDir>/js/export/export_word_main_flow_children.ts',
    '^.+[\\\\/]export_word_main_flow_document\\.js$': '<rootDir>/js/export/export_word_main_flow_document.ts',
    '^.+[\\\\/]export_word_deprecated_text_export\\.js$': '<rootDir>/js/export/export_word_deprecated_text_export.ts',
    '^.+[\\\\/]export_html_build\\.js$': '<rootDir>/js/export/export_html_build.ts',
    '^.+[\\\\/]export_html_build_primitives\\.js$': '<rootDir>/js/export/export_html_build_primitives.ts',
    '^.+[\\\\/]export_html_build_layouts\\.js$': '<rootDir>/js/export/export_html_build_layouts.ts',
    '^.+[\\\\/]export_html_audit_hash\\.js$': '<rootDir>/js/export/export_html_audit_hash.ts',
    '^.+[\\\\/]export_html_styles_generated\\.js$': '<rootDir>/js/export/export_html_styles_generated.ts',
    '^.+[\\\\/]export_html_script_generated\\.js$': '<rootDir>/js/export/export_html_script_generated.ts',
    '^.+[\\\\/]export_html_export\\.js$': '<rootDir>/js/export/export_html_export.ts',
    '^.+/state/index\\.js$': '<rootDir>/js/state/index.ts',
    '^.+/actionTypes\\.js$': '<rootDir>/js/state/actionTypes.ts',
    '^.+/audit_reducer_bulk_pass\\.js$': '<rootDir>/js/state/audit_reducer_bulk_pass.ts',
    '^.+/bulk_pass_unreviewed_policy\\.js$': '<rootDir>/js/logic/bulk_pass_unreviewed_policy.ts',
    '^.+/sample_bulk_pass_not_audited_gate\\.js$': '<rootDir>/js/logic/sample_bulk_pass_not_audited_gate.ts',
    '^.+/auditReducer\\.js$': '<rootDir>/js/state/auditReducer.ts',
    '^.+/audit_reducer_time\\.js$': '<rootDir>/js/state/audit_reducer_time.ts',
    '^.+/auditResultAliases\\.js$': '<rootDir>/js/state/auditResultAliases.ts',
    '^.+/metadataHandlers\\.js$': '<rootDir>/js/state/metadataHandlers.ts',
    '^.+/auditStatusHandlers\\.js$': '<rootDir>/js/state/auditStatusHandlers.ts',
    '^.+/sampleHandlers\\.js$': '<rootDir>/js/state/sampleHandlers.ts',
    '^.+/sample_edit_diff\\.js$': '<rootDir>/js/logic/sample_edit_diff.ts',
    '^.+/remoteStateHandlers\\.js$': '<rootDir>/js/state/remoteStateHandlers.ts',
    '^.+/same_user_tab_field_sync\\.js$': '<rootDir>/js/logic/same_user_tab_field_sync.ts',
    '^.+/RequirementAuditComponent\\.js$': '<rootDir>/js/components/RequirementAuditComponent.ts',
    '^.+[\\\\/]krav_vy_knapp_debug_log\\.js$': '<rootDir>/js/components/requirement_audit/krav_vy_knapp_debug_log.ts',
    '^.+[\\\\/]criteria_panel\\.js$': '<rootDir>/js/components/requirement_audit/criteria_panel.ts',
    '^.+/RequirementAuditSidebarComponent\\.js$': '<rootDir>/js/components/RequirementAuditSidebarComponent.ts',
    '^.+/AuditActionsViewComponent\\.js$': '<rootDir>/js/components/AuditActionsViewComponent.ts',
    '^.+/SampleManagementViewComponent\\.js$': '<rootDir>/js/components/SampleManagementViewComponent.ts',
    '^.+/AuditProblemsViewComponent\\.js$': '<rootDir>/js/components/AuditProblemsViewComponent.ts',
    '^.+/ConfirmUpdatesViewComponent\\.js$': '<rootDir>/js/components/ConfirmUpdatesViewComponent.ts',
    '^.+/FinalConfirmUpdatesViewComponent\\.js$': '<rootDir>/js/components/FinalConfirmUpdatesViewComponent.ts',
    '^.+/SampleListComponent\\.js$': '<rootDir>/js/components/SampleListComponent.ts',
    '^.+/requirement_list_query\\.js$': '<rootDir>/js/components/requirements_list/requirement_list_query.ts',
    '^.+/requirement_list_filter_requirements\\.js$':
      '<rootDir>/js/components/requirements_list/requirement_list_filter_requirements.ts',
    '^.+/requirement_list_incremental_dom\\.js$':
      '<rootDir>/js/components/requirements_list/requirement_list_incremental_dom.ts',
    '^.+/requirement_list_list_items\\.js$': '<rootDir>/js/components/requirements_list/requirement_list_list_items.ts',
    '^.+/requirement_list_mark_all_modal\\.js$':
      '<rootDir>/js/components/requirements_list/requirement_list_mark_all_modal.ts',
    '^.+/requirement_search_utils\\.js$': '<rootDir>/js/utils/requirement_search_utils.ts',
    '^.+/requirement_deficiency_search\\.js$': '<rootDir>/js/utils/requirement_deficiency_search.ts',
    '^.+/string_filter_normalize\\.js$': '<rootDir>/js/utils/string_filter_normalize.ts',
    '^.+/filename_utils\\.js$': '<rootDir>/js/utils/filename_utils.ts',
    '^.+/download_filename_utils\\.js$': '<rootDir>/js/utils/download_filename_utils.ts',
    '^.+[\\\\/]build_reload_url\\.js$': '<rootDir>/js/utils/build_reload_url.ts',
    '^.+[\\\\/]hard_reload_page\\.js$': '<rootDir>/js/utils/hard_reload_page.ts',
    '^.+[\\\\/]save_audit_backup_before_reload\\.js$': '<rootDir>/js/utils/save_audit_backup_before_reload.ts',
    '^.+/traverse_audit_data\\.js$': '<rootDir>/js/utils/traverse_audit_data.ts',
    '^.+/draft_manager\\.js$': '<rootDir>/js/draft_manager.ts',
    '^.+[\\\\/]requirement_lookup\\.js$': '<rootDir>/js/logic/requirement_lookup.ts',
    '^.+/SideMenuComponent\\.js$': '<rootDir>/js/components/SideMenuComponent.ts',
    '^.+/rulefile_updater_logic\\.js$': '<rootDir>/js/logic/rulefile_updater_logic.ts',
    '^.+/validation_logic\\.js$': '<rootDir>/js/validation_logic.ts',
    '^.+[\\\\/]validation_rulefile_requirements\\.js$': '<rootDir>/js/logic/validation_rulefile_requirements.ts',
    '^.+[\\\\/]sanitize_persisted_app_state\\.js$': '<rootDir>/js/logic/sanitize_persisted_app_state.ts',
    '^.+[\\\\/]audit_sync_tracking\\.js$': '<rootDir>/js/logic/audit_sync_tracking.ts',
    '^.+[\\\\/]prepared_audit_sync\\.js$': '<rootDir>/js/logic/prepared_audit_sync.ts',
    '^.+[\\\\/]audit_remote_push_apply\\.js$': '<rootDir>/js/logic/audit_remote_push_apply.ts',
    '^.+[\\\\/]audit_sync_planning\\.js$': '<rootDir>/js/sync/audit_sync_planning.ts',
    '^.+[\\\\/]audit_sync_execute\\.js$': '<rootDir>/js/sync/audit_sync_execute.ts',
    '^.+[\\\\/]audit_sync_prepare\\.js$': '<rootDir>/js/sync/audit_sync_prepare.ts',
    '^.+[\\\\/]audit_sync_service\\.js$': '<rootDir>/js/sync/audit_sync_service.ts',
    '^.+[\\\\/]audit_sync_unload\\.js$': '<rootDir>/js/sync/audit_sync_unload.ts',
    '^.+[\\\\/]sync_payload_mapper\\.js$': '<rootDir>/js/sync/sync_payload_mapper.ts',
    '^.+[\\\\/]unload_persist_registry\\.js$': '<rootDir>/js/logic/unload_persist_registry.ts',
    '^.+[\\\\/]coerce_audit_for_export\\.js$': '<rootDir>/js/logic/coerce_audit_for_export.ts',
    '^.+[\\\\/]table_pagination_logic\\.js$': '<rootDir>/js/logic/table_pagination_logic.ts',
    '^.+[\\\\/]audit_list_case_grouping\\.js$': '<rootDir>/js/logic/audit_list_case_grouping.ts',
    '^.+[\\\\/]audit_list_view_transition\\.js$': '<rootDir>/js/logic/audit_list_view_transition.ts',
    '^.+/translation_logic\\.js$': '<rootDir>/js/translation_logic.ts',
    '^.+/requirement_audit_url_ui\\.js$': '<rootDir>/js/logic/requirement_audit_url_ui.ts',
    '^.+/requirements_list_filters_url_ui\\.js$': '<rootDir>/js/logic/requirements_list_filters_url_ui.ts',
    '^.+/migrate_legacy_query_to_hash\\.js$': '<rootDir>/js/logic/migrate_legacy_query_to_hash.ts',
    '^.+/shareable_app_location\\.js$': '<rootDir>/js/logic/shareable_app_location.ts',
    '^.+[\\\\/]sanitize_media_filename\\.js$': '<rootDir>/shared/media/sanitize_media_filename.ts',
    '^.+[\\\\/]client_media_validation\\.js$': '<rootDir>/shared/media/client_media_validation.ts',
    '^.+[\\\\/]media_upload_limits\\.js$': '<rootDir>/shared/constants/media_upload_limits.ts',
    '^.+[\\\\/]browser_online\\.js$': '<rootDir>/js/utils/browser_online.ts',
    '^.+[\\\\/]pending_audit_media_deletes\\.js$': '<rootDir>/js/sync/pending_audit_media_deletes.ts',
    '^.+[\\\\/]attach_media_upload_queue\\.js$': '<rootDir>/js/components/media/attach_media_upload_queue.ts',
    '^.+[\\\\/]attach_media_duplicate_filename_status\\.js$':
      '<rootDir>/js/components/media/attach_media_duplicate_filename_status.ts',
    '^.+[\\\\/]audit_media_api\\.js$': '<rootDir>/js/api/audit_media_api.ts',
    '^.+[\\\\/]audit_attached_media_references\\.js$': '<rootDir>/js/logic/audit_attached_media_references.ts',
    '^.+[\\\\/]attach_media_file_drop_zone\\.js$': '<rootDir>/js/components/media/attach_media_file_drop_zone.ts',
    '^.+[\\\\/]render_audit_media_list_item\\.js$': '<rootDir>/js/components/media/render_audit_media_list_item.ts',
    '^.+[\\\\/]audit_media_storage\\.js$': '<rootDir>/server/media/audit_media_storage.ts',
    '^.+[\\\\/]audit_grouped_list_render\\.js$': '<rootDir>/js/components/audit_grouped_list_render.ts',
    '^.+[\\\\/]audit_group_row_ui\\.js$': '<rootDir>/js/components/audit_group_row_ui.ts',
    '^.+[\\\\/]audit_group_detail_table\\.js$': '<rootDir>/js/components/audit_group_detail_table.ts',
    '^.+[\\\\/]audit_group_actor_edit_modal\\.js$': '<rootDir>/js/components/audit_group_actor_edit_modal.ts',
    '^.+[\\\\/]AuditGroupedListComponent\\.js$': '<rootDir>/js/components/AuditGroupedListComponent.ts',
    '^.+[\\\\/]attach_media_modal_remove_flow\\.js$': '<rootDir>/js/components/media/attach_media_modal_remove_flow.ts',
    '^.+[\\\\/]attach_media_modal_setup\\.js$': '<rootDir>/js/components/media/attach_media_modal_setup.ts',
    '^.+[\\\\/]attach_media_in_modal_remove_confirm\\.js$':
      '<rootDir>/js/components/media/attach_media_in_modal_remove_confirm.ts',
    '^.+[\\\\/]attach_media_modal_list_focus\\.js$': '<rootDir>/js/components/media/attach_media_modal_list_focus.ts',
    '^.+[\\\\/]attach_media_modal_online_upload\\.js$': '<rootDir>/js/components/media/attach_media_modal_online_upload.ts',
    '^.+[\\\\/]attach_media_modal_persist\\.js$': '<rootDir>/js/components/media/attach_media_modal_persist.ts',
    '^.+[\\\\/]attach_media_modal_list\\.js$': '<rootDir>/js/components/media/attach_media_modal_list.ts',
    '^.+[\\\\/]attach_media_modal_status\\.js$': '<rootDir>/js/components/media/attach_media_modal_status.ts',
    '^.+[\\\\/]attach_media_modal_view_switch\\.js$': '<rootDir>/js/components/media/attach_media_modal_view_switch.ts',
    '^.+[\\\\/]attach_media_in_modal_preview\\.js$': '<rootDir>/js/components/media/attach_media_in_modal_preview.ts',
    '^.+[\\\\/]open_audit_media_image_preview\\.js$': '<rootDir>/js/components/media/open_audit_media_image_preview.ts',
    '^.+[\\\\/]audit_media_image_preview_mount\\.js$': '<rootDir>/js/components/media/audit_media_image_preview_mount.ts',
    '^.+[\\\\/]audit_media_preview_observation\\.js$': '<rootDir>/js/components/media/audit_media_preview_observation.ts',
    '^.+[\\\\/]entity_id_match\\.js$': '<rootDir>/js/logic/entity_id_match.ts',
    '^.+[\\\\/]vite_import_meta_hot\\.js$': '<rootDir>/tests/mocks/vite_import_meta_hot.js',
    '^.+[\\\\/]audit_list_last_updated\\.js$': '<rootDir>/js/logic/audit_list_last_updated.ts',
  },
  testMatch: [
    '<rootDir>/tests/unit/**/*.spec.js',
    '<rootDir>/tests/unit/**/*.spec.ts',
  ],
  testPathIgnorePatterns: ['/node_modules/', '.e2e.spec.js'],
  /** Tillåt transpilering av marked (ESM) så js/utils/markdown.ts kan laddas i Jest. */
  transformIgnorePatterns: ['/node_modules/(?!(marked)/)'],
  transform: {
    '^.+\\.(t|j)s$': [
      '@swc/jest',
      {
        jsc: {
          parser: {
            syntax: 'typescript',
          },
          target: 'es2022',
        },
        module: {
          type: 'es6',
        },
      },
    ],
  },
  extensionsToTreatAsEsm: ['.ts'],
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  collectCoverageFrom: [
    'js/logic/**/*.{js,ts}',
    'js/api/**/*.{js,ts}',
    'js/state/**/*.{js,ts}',
    '!js/**/*.spec.{js,ts}',
  ],
};
