export default {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/tests/setup-jest.js'],
  moduleNameMapper: {
    '\\.(css)$': '<rootDir>/tests/styleMock.js',
    // Migrerade moduler: import behåller .js (Vite/TS) men filen heter .ts — Jest behöver explicit mappning.
    '^.+/audit_logic\\.js$': '<rootDir>/js/audit_logic.ts',
    '^.+/audit_logic_types\\.js$': '<rootDir>/js/logic/audit_logic_types.ts',
    '^.+/audit_logic_i18n\\.js$': '<rootDir>/js/logic/audit_logic_i18n.ts',
    '^.+/audit_logic_lookup\\.js$': '<rootDir>/js/logic/audit_logic_lookup.ts',
    '^.+/audit_logic_status\\.js$': '<rootDir>/js/logic/audit_logic_status.ts',
    '^.+[\\\\/]entity_id_match\\.js$': '<rootDir>/js/logic/entity_id_match.ts',
    '^.+/audit_logic_deficiency\\.js$': '<rootDir>/js/logic/audit_logic_deficiency.ts',
    '^.+/audit_logic_requirements_lists\\.js$': '<rootDir>/js/logic/audit_logic_requirements_lists.ts',
    '^.+/audit_logic_progress\\.js$': '<rootDir>/js/logic/audit_logic_progress.ts',
    '^.+/audit_logic_recalc\\.js$': '<rootDir>/js/logic/audit_logic_recalc.ts',
    '^.+/audit_list_last_updated\\.js$': '<rootDir>/js/logic/audit_list_last_updated.ts',
    '^.+/audit_list_progress\\.js$': '<rootDir>/js/logic/audit_list_progress.ts',
    '^.+/closed_audit_assessment_gap_fill\\.js$': '<rootDir>/js/logic/closed_audit_assessment_gap_fill.ts',
    '^.+/requirement_assessment_gap_fill\\.js$': '<rootDir>/js/logic/requirement_assessment_gap_fill.ts',
    '^.+/audit_logic_problems_media\\.js$': '<rootDir>/js/logic/audit_logic_problems_media.ts',
    '^.+/ScoreCalculator\\.js$': '<rootDir>/js/logic/ScoreCalculator.ts',
    '^.+/score_calculator_passed_check_failures\\.js$': '<rootDir>/js/logic/score_calculator_passed_check_failures.ts',
    '^.+/export_logic\\.js$': '<rootDir>/js/export_logic.ts',
    '^.+[\\\\/]export_format_helpers\\.js$': '<rootDir>/js/export/export_format_helpers.ts',
    '^.+[\\\\/]export_taxonomy_mapping\\.js$': '<rootDir>/js/export/export_taxonomy_mapping.ts',
    '^.+[\\\\/]deficiency_id_display\\.js$': '<rootDir>/js/utils/deficiency_id_display.ts',
    '^.+[\\\\/]export_bootstrap\\.js$': '<rootDir>/js/export/export_bootstrap.ts',
    '^.+[\\\\/]export_csv\\.js$': '<rootDir>/js/export/export_csv.ts',
    '^.+[\\\\/]export_deficiency_rows\\.js$': '<rootDir>/js/export/export_deficiency_rows.ts',
    '^.+[\\\\/]export_media_filename\\.js$': '<rootDir>/js/export/export_media_filename.ts',
    '^.+[\\\\/]export_media_filename_context\\.js$': '<rootDir>/js/export/export_media_filename_context.ts',
    '^.+[\\\\/]export_media_naming\\.js$': '<rootDir>/js/export/export_media_naming.ts',
    '^.+[\\\\/]export_deficiency_traversal\\.js$': '<rootDir>/js/export/export_deficiency_traversal.ts',
    '^.+[\\\\/]export_excel\\.js$': '<rootDir>/js/export/export_excel.ts',
    '^.+[\\\\/]excel_export_helpers\\.js$': '<rootDir>/js/export/excel_export_helpers.ts',
    '^.+[\\\\/]excel_deficiencies_sheet\\.js$': '<rootDir>/js/export/excel_deficiencies_sheet.ts',
    '^.+[\\\\/]export_word_markdown_docx\\.js$': '<rootDir>/js/export/export_word_markdown_docx.ts',
    '^.+[\\\\/]export_word_requirement_sections\\.js$': '<rootDir>/js/export/export_word_requirement_sections.ts',
    '^.+[\\\\/]export_word_deficiency_queries\\.js$': '<rootDir>/js/export/export_word_deficiency_queries.ts',
    '^.+[\\\\/]export_word_detail_pages\\.js$': '<rootDir>/js/export/export_word_detail_pages.ts',
    '^.+[\\\\/]export_word_main_flow\\.js$': '<rootDir>/js/export/export_word_main_flow.ts',
    '^.+[\\\\/]export_word_main_flow_children\\.js$': '<rootDir>/js/export/export_word_main_flow_children.ts',
    '^.+[\\\\/]export_word_main_flow_document\\.js$': '<rootDir>/js/export/export_word_main_flow_document.ts',
    '^.+[\\\\/]export_report_filename\\.js$': '<rootDir>/js/export/export_report_filename.ts',
    '^.+[\\\\/]export_report_typography\\.js$': '<rootDir>/js/export/export_report_typography.ts',
    '^.+[\\\\/]export_report_html_criterias\\.js$': '<rootDir>/js/export/export_report_html_criterias.ts',
    '^.+[\\\\/]export_deficiency_types_collect\\.js$': '<rootDir>/js/export/export_deficiency_types_collect.ts',
    '^.+[\\\\/]export_report_html_deficiency_types\\.js$': '<rootDir>/js/export/export_report_html_deficiency_types.ts',
    '^.+[\\\\/]export_report_html_appendix1_summary\\.js$': '<rootDir>/js/export/export_report_html_appendix1_summary.ts',
    '^.+[\\\\/]export_report_html_appendix1_pts\\.js$': '<rootDir>/js/export/export_report_html_appendix1_pts.ts',
    '^.+[\\\\/]export_report_appendix1_print_css\\.js$': '<rootDir>/js/export/export_report_appendix1_print_css.ts',
    '^.+[\\\\/]export_word_appendix1_pts\\.js$': '<rootDir>/js/export/export_word_appendix1_pts.ts',
    '^.+[\\\\/]export_word_deficiency_types\\.js$': '<rootDir>/js/export/export_word_deficiency_types.ts',
    '^.+[\\\\/]export_word_appendix1_summary\\.js$': '<rootDir>/js/export/export_word_appendix1_summary.ts',
    '^.+[\\\\/]export_html_to_word_paragraphs\\.js$': '<rootDir>/js/export/export_html_to_word_paragraphs.ts',
    '^.+[\\\\/]appendix1_summary_legacy\\.js$': '<rootDir>/js/logic/appendix1_summary_legacy.ts',
    '^.+[\\\\/]appendix1_summary_text\\.js$': '<rootDir>/js/logic/appendix1_summary_text.ts',
    '^.+[\\\\/]appendix1_sections\\.js$': '<rootDir>/js/logic/appendix1_sections.ts',
    '^.+[\\\\/]appendix1_principle_intro\\.js$': '<rootDir>/js/logic/appendix1_principle_intro.ts',
    '^.+[\\\\/]appendix1_sections_defaults\\.js$': '<rootDir>/js/logic/appendix1_sections_defaults.ts',
    '^.+[\\\\/]appendix1_sections_export\\.js$': '<rootDir>/js/logic/appendix1_sections_export.ts',
    '^.+[\\\\/]appendix1_sections_normalize\\.js$': '<rootDir>/js/logic/appendix1_sections_normalize.ts',
    '^.+[\\\\/]appendix1_sections_migrate\\.js$': '<rootDir>/js/logic/appendix1_sections_migrate.ts',
    '^.+[\\\\/]appendix1_sections_types\\.js$': '<rootDir>/js/logic/appendix1_sections_types.ts',
    '^.+[\\\\/]shared/classification/taxonomy_grouping\\.js$':
      '<rootDir>/shared/classification/taxonomy_grouping.ts',
    '^.+[\\\\/]taxonomy_usage\\.js$': '<rootDir>/js/logic/taxonomy_usage.ts',
    '^.+[\\\\/]taxonomy_persist\\.js$': '<rootDir>/js/logic/taxonomy_persist.ts',
    '^.+[\\\\/]rulefile_taxonomy_keys\\.js$':
      '<rootDir>/js/components/rulefile_sections/rulefile_taxonomy_keys.ts',
    '^.+[\\\\/]rulefile_content_type_keys\\.js$':
      '<rootDir>/js/components/rulefile_sections/rulefile_content_type_keys.ts',
    '^.+[\\\\/]rulefile_content_type_requirements\\.js$':
      '<rootDir>/js/components/rulefile_sections/rulefile_content_type_requirements.ts',
    '^.+[\\\\/]rulefile_content_types_ui\\.js$':
      '<rootDir>/js/components/rulefile_sections/rulefile_content_types_ui.ts',
    '^.+[\\\\/]rulefile_content_type_edit_ui\\.js$':
      '<rootDir>/js/components/rulefile_sections/rulefile_content_type_edit_ui.ts',
    '^.+[\\\\/]rulefile_taxonomy_principles_editor_ui\\.js$':
      '<rootDir>/js/components/rulefile_sections/rulefile_taxonomy_principles_editor_ui.ts',
    '^.+[\\\\/]rulefile_taxonomy_principle_intro_ui\\.js$':
      '<rootDir>/js/components/rulefile_sections/rulefile_taxonomy_principle_intro_ui.ts',
    '^.+[\\\\/]rulefile_appendix1_sections_editor_ui\\.js$':
      '<rootDir>/js/components/rulefile_sections/rulefile_appendix1_sections_editor_ui.ts',
    '^.+[\\\\/]rulefile_appendix1_deficiency_intros_editor_ui\\.js$':
      '<rootDir>/js/components/rulefile_sections/rulefile_appendix1_deficiency_intros_editor_ui.ts',
    '^.+[\\\\/]EditReportTemplateAppendix1Component\\.js$':
      '<rootDir>/js/components/rulefile_sections/EditReportTemplateAppendix1Component.ts',
    '^.+[\\\\/]shared/pdf/appendix1_toc_page_numbers\\.js$':
      '<rootDir>/shared/pdf/appendix1_toc_page_numbers.ts',
    '^.+[\\\\/]requirement_classifications\\.js$': '<rootDir>/js/logic/requirement_classifications.ts',
    '^.+[\\\\/]appendix1_cover_image\\.js$': '<rootDir>/server/services/appendix1_cover_image.ts',
    '^.+[\\\\/]appendix1_toc_page_numbers\\.js$': '<rootDir>/server/services/appendix1_toc_page_numbers.ts',
    '^.+[\\\\/]appendix1_toc_browser_scripts_loader\\.js$':
      '<rootDir>/server/services/appendix1_toc_browser_scripts_loader.ts',
    '^.+[\\\\/]export_screenshots_appendix_collect\\.js$': '<rootDir>/js/export/export_screenshots_appendix_collect.ts',
    '^.+[\\\\/]export_screenshots_appendix_media\\.js$': '<rootDir>/js/export/export_screenshots_appendix_media.ts',
    '^.+[\\\\/]export_screenshots_appendix_pdf_encode\\.js$': '<rootDir>/js/export/export_screenshots_appendix_pdf_encode.ts',
    '^.+[\\\\/]export_report_html_screenshots_appendix\\.js$': '<rootDir>/js/export/export_report_html_screenshots_appendix.ts',
    '^.+[\\\\/]export_word_screenshots_appendix\\.js$': '<rootDir>/js/export/export_word_screenshots_appendix.ts',
    '^.+[\\\\/]export_pdf_main_flow\\.js$': '<rootDir>/js/export/export_pdf_main_flow.ts',
    '^.+[\\\\/]export_pdf_user_errors\\.js$': '<rootDir>/js/export/export_pdf_user_errors.ts',
    '^.+[\\\\/]export_pdf_html_size_error\\.js$': '<rootDir>/js/export/export_pdf_html_size_error.ts',
    '^.+[\\\\/]export_error_handling\\.js$': '<rootDir>/js/export/export_error_handling.ts',
    '^.+[\\\\/]export_word_deprecated_text_export\\.js$': '<rootDir>/js/export/export_word_deprecated_text_export.ts',
    '^.+[\\\\/]export_html_build\\.js$': '<rootDir>/js/export/export_html_build.ts',
    '^.+[\\\\/]export_html_build_primitives\\.js$': '<rootDir>/js/export/export_html_build_primitives.ts',
    '^.+[\\\\/]export_html_build_layouts\\.js$': '<rootDir>/js/export/export_html_build_layouts.ts',
    '^.+[\\\\/]export_html_audit_hash\\.js$': '<rootDir>/js/export/export_html_audit_hash.ts',
    '^.+[\\\\/]export_html_styles_generated\\.js$': '<rootDir>/js/export/export_html_styles_generated.ts',
    '^.+[\\\\/]export_html_script_generated\\.js$': '<rootDir>/js/export/export_html_script_generated.ts',
    '^.+[\\\\/]export_html_export\\.js$': '<rootDir>/js/export/export_html_export.ts',
    '^.+[\\\\/]export_images_zip_export\\.js$': '<rootDir>/js/export/export_images_zip_export.ts',
    '^.+[\\\\/]export_audit_appendices_zip\\.js$': '<rootDir>/js/export/export_audit_appendices_zip.ts',
    '^.+[\\\\/]export_observation_texts_collect\\.js$': '<rootDir>/js/export/export_observation_texts_collect.ts',
    '^.+[\\\\/]export_observation_texts_word\\.js$': '<rootDir>/js/export/export_observation_texts_word.ts',
    '^.+[\\\\/]export_observation_texts_word_blocks\\.js$': '<rootDir>/js/export/export_observation_texts_word_blocks.ts',
    '^.+[\\\\/]export_observation_texts_word_constants\\.js$': '<rootDir>/js/export/export_observation_texts_word_constants.ts',
    '^.+[\\\\/]export_word_observation_body_paragraphs\\.js$': '<rootDir>/js/export/export_word_observation_body_paragraphs.ts',
    '^.+[\\\\/]import/parse_observation_word_handling_docx\\.js$': '<rootDir>/js/import/parse_observation_word_handling_docx.ts',
    '^.+[\\\\/]import/docx_paragraphs_to_markdown\\.js$': '<rootDir>/js/import/docx_paragraphs_to_markdown.ts',
    '^.+[\\\\/]import/observation_word_import_diff\\.js$': '<rootDir>/js/import/observation_word_import_diff.ts',
    '^.+[\\\\/]import/observation_word_import_apply\\.js$': '<rootDir>/js/import/observation_word_import_apply.ts',
    '^.+[\\\\/]import/observation_word_import_types\\.js$': '<rootDir>/js/import/observation_word_import_types.ts',
    '^.+/parse_observation_word_handling_docx\\.js$': '<rootDir>/js/import/parse_observation_word_handling_docx.ts',
    '^.+/docx_paragraphs_to_markdown\\.js$': '<rootDir>/js/import/docx_paragraphs_to_markdown.ts',
    '^.+/observation_word_import_diff\\.js$': '<rootDir>/js/import/observation_word_import_diff.ts',
    '^.+/observation_word_import_apply\\.js$': '<rootDir>/js/import/observation_word_import_apply.ts',
    '^.+/observation_word_import_types\\.js$': '<rootDir>/js/import/observation_word_import_types.ts',
    '^.+[\\\\/]state/audit_reducer_observation_word_import\\.js$': '<rootDir>/js/state/audit_reducer_observation_word_import.ts',
    '^.+/audit_reducer_observation_word_import\\.js$': '<rootDir>/js/state/audit_reducer_observation_word_import.ts',
    '^.+/shared/export/observation_word_audit_marker\\.js$': '<rootDir>/shared/export/observation_word_audit_marker.ts',
    '^.+[\\\\/]observation_word_audit_marker\\.js$': '<rootDir>/shared/export/observation_word_audit_marker.ts',
    '^.+/word_file_validation\\.js$': '<rootDir>/shared/import/word_file_validation.ts',
    '^.+/shared/import/clipboard_word_files\\.js$': '<rootDir>/shared/import/clipboard_word_files.ts',
    '^.+[\\\\/]import/clipboard_word_files\\.js$': '<rootDir>/shared/import/clipboard_word_files.ts',
    '^.+[\\\\/]observation_word_import/observation_word_import_modal\\.js$':
      '<rootDir>/js/components/observation_word_import/observation_word_import_modal.ts',
    '^.+[\\\\/]observation_word_import/observation_word_import_modal_setup\\.js$':
      '<rootDir>/js/components/observation_word_import/observation_word_import_modal_setup.ts',
    '^.+[\\\\/]observation_word_import/observation_word_file_drop_zone\\.js$':
      '<rootDir>/js/components/observation_word_import/observation_word_file_drop_zone.ts',
    '^.+/observation_word_import_modal\\.js$': '<rootDir>/js/components/observation_word_import/observation_word_import_modal.ts',
    '^.+/observation_word_import_modal_setup\\.js$':
      '<rootDir>/js/components/observation_word_import/observation_word_import_modal_setup.ts',
    '^.+/observation_word_file_drop_zone\\.js$':
      '<rootDir>/js/components/observation_word_import/observation_word_file_drop_zone.ts',
    '^.+[\\\\/]export_html_media\\.js$': '<rootDir>/js/export/export_html_media.ts',
    '^.+[\\\\/]export_html_themes\\.js$': '<rootDir>/js/export/export_html_themes.ts',
    '^.+[\\\\/]export_html_sidebar_script\\.js$': '<rootDir>/js/export/export_html_sidebar_script.ts',
    '^.+/state/index\\.js$': '<rootDir>/js/state/index.ts',
    '^.+/actionTypes\\.js$': '<rootDir>/js/state/actionTypes.ts',
    '^.+/audit_reducer_bulk_pass\\.js$': '<rootDir>/js/state/audit_reducer_bulk_pass.ts',
    '^.+/bulk_pass_unreviewed_policy\\.js$': '<rootDir>/js/logic/bulk_pass_unreviewed_policy.ts',
    '^.+/sample_bulk_pass_not_audited_gate\\.js$': '<rootDir>/js/logic/sample_bulk_pass_not_audited_gate.ts',
    '^.+/auditReducer\\.js$': '<rootDir>/js/state/auditReducer.ts',
    '^.+/audit_reducer_time\\.js$': '<rootDir>/js/state/audit_reducer_time.ts',
    '^.+/auditResultAliases\\.js$': '<rootDir>/js/state/auditResultAliases.ts',
    '^.+/metadataHandlers\\.js$': '<rootDir>/js/state/metadataHandlers.ts',
    '^.+/auditStatusHandlers\\.js$': '<rootDir>/js/state/auditStatusHandlers.ts',
    '^.+/sampleHandlers\\.js$': '<rootDir>/js/state/sampleHandlers.ts',
    '^.+/sample_edit_diff\\.js$': '<rootDir>/js/logic/sample_edit_diff.ts',
    '^.+/remoteStateHandlers\\.js$': '<rootDir>/js/state/remoteStateHandlers.ts',
    '^.+/same_user_tab_field_sync\\.js$': '<rootDir>/js/logic/same_user_tab_field_sync.ts',
    '^.+/RequirementAuditComponent\\.js$': '<rootDir>/js/components/RequirementAuditComponent.ts',
    '^.+[\\\\/]krav_vy_knapp_debug_log\\.js$': '<rootDir>/js/components/requirement_audit/krav_vy_knapp_debug_log.ts',
    '^.+[\\\\/]criteria_panel\\.js$': '<rootDir>/js/components/requirement_audit/criteria_panel.ts',
    '^.+[\\\\/]ChecklistHandler\\.js$': '<rootDir>/js/components/requirement_audit/ChecklistHandler.ts',
    '^.+/RequirementAuditSidebarComponent\\.js$': '<rootDir>/js/components/RequirementAuditSidebarComponent.ts',
    '^.+/AuditActionsViewComponent\\.js$': '<rootDir>/js/components/AuditActionsViewComponent.ts',
    '^.+[\\\\/]audit_actions_view_ui\\.js$': '<rootDir>/js/components/audit_actions_view_ui.ts',
    '^.+[\\\\/]audit_actions_view_sections\\.js$': '<rootDir>/js/components/audit_actions_view_sections.ts',
    '^.+[\\\\/]audit_actions_export_section\\.js$': '<rootDir>/js/components/audit_actions_export_section.ts',
    '^.+[\\\\/]audit_actions_view_export_handlers\\.js$': '<rootDir>/js/components/audit_actions_view_export_handlers.ts',
    '^.+[\\\\/]audit_actions_view_status_section\\.js$': '<rootDir>/js/components/audit_actions_view_status_section.ts',
    '^.+[\\\\/]audit_actions_view_status_select\\.js$': '<rootDir>/js/components/audit_actions_view_status_select.ts',
    '^.+[\\\\/]audit_actions_render\\.js$': '<rootDir>/js/components/audit_actions_render.ts',
    '^.+[\\\\/]audit_actions_view_content_transition\\.js$': '<rootDir>/js/components/audit_actions_view_content_transition.ts',
    '^.+/SampleManagementViewComponent\\.js$': '<rootDir>/js/components/SampleManagementViewComponent.ts',
    '^.+/AuditProblemsViewComponent\\.js$': '<rootDir>/js/components/AuditProblemsViewComponent.ts',
    '^.+/ConfirmUpdatesViewComponent\\.js$': '<rootDir>/js/components/ConfirmUpdatesViewComponent.ts',
    '^.+/FinalConfirmUpdatesViewComponent\\.js$': '<rootDir>/js/components/FinalConfirmUpdatesViewComponent.ts',
    '^.+/SampleListComponent\\.js$': '<rootDir>/js/components/SampleListComponent.ts',
    '^.+/requirement_list_query\\.js$': '<rootDir>/js/components/requirements_list/requirement_list_query.ts',
    '^.+/requirement_list_filter_requirements\\.js$':
      '<rootDir>/js/components/requirements_list/requirement_list_filter_requirements.ts',
    '^.+/requirement_list_incremental_dom\\.js$':
      '<rootDir>/js/components/requirements_list/requirement_list_incremental_dom.ts',
    '^.+/requirement_list_list_items\\.js$': '<rootDir>/js/components/requirements_list/requirement_list_list_items.ts',
    '^.+/requirement_list_mark_all_modal\\.js$':
      '<rootDir>/js/components/requirements_list/requirement_list_mark_all_modal.ts',
    '^.+/requirement_search_utils\\.js$': '<rootDir>/js/utils/requirement_search_utils.ts',
    '^.+/requirement_deficiency_search\\.js$': '<rootDir>/js/utils/requirement_deficiency_search.ts',
    '^.+/string_filter_normalize\\.js$': '<rootDir>/js/utils/string_filter_normalize.ts',
    '^.+/filename_utils\\.js$': '<rootDir>/js/utils/filename_utils.ts',
    '^.+/download_filename_utils\\.js$': '<rootDir>/js/utils/download_filename_utils.ts',
    '^.+[\\\\/]generic_tooltip\\.js$': '<rootDir>/js/utils/generic_tooltip.ts',
    '^.+[\\\\/]file_download_button_ui\\.js$': '<rootDir>/js/utils/file_download_button_ui.ts',
    '^.+[\\\\/]build_reload_url\\.js$': '<rootDir>/js/utils/build_reload_url.ts',
    '^.+[\\\\/]hard_reload_page\\.js$': '<rootDir>/js/utils/hard_reload_page.ts',
    '^.+[\\\\/]save_audit_backup_before_reload\\.js$': '<rootDir>/js/utils/save_audit_backup_before_reload.ts',
    '^.+/traverse_audit_data\\.js$': '<rootDir>/js/utils/traverse_audit_data.ts',
    '^.+/draft_manager\\.js$': '<rootDir>/js/draft_manager.ts',
    '^.+[\\\\/]requirement_lookup\\.js$': '<rootDir>/js/logic/requirement_lookup.ts',
    '^.+/SideMenuComponent\\.js$': '<rootDir>/js/components/SideMenuComponent.ts',
    '^.+/rulefile_updater_logic\\.js$': '<rootDir>/js/logic/rulefile_updater_logic.ts',
    '^.+/validation_logic\\.js$': '<rootDir>/js/validation_logic.ts',
    '^.+[\\\\/]validation_rulefile_requirements\\.js$': '<rootDir>/js/logic/validation_rulefile_requirements.ts',
    '^.+[\\\\/]sanitize_persisted_app_state\\.js$': '<rootDir>/js/logic/sanitize_persisted_app_state.ts',
    '^.+[\\\\/]audit_user_requirement_resume\\.js$': '<rootDir>/js/logic/audit_user_requirement_resume.ts',
    '^.+[\\\\/]auditUserResumeHandlers\\.js$': '<rootDir>/js/state/auditUserResumeHandlers.ts',
    '^.+[\\\\/]audit_overview_continue_audit\\.js$': '<rootDir>/js/components/audit_overview_continue_audit.ts',
    '^.+[\\\\/]audit_overview_score_panel\\.js$': '<rootDir>/js/components/audit_overview_score_panel.ts',
    '^.+[\\\\/]audit_sync_tracking\\.js$': '<rootDir>/js/logic/audit_sync_tracking.ts',
    '^.+[\\\\/]audit_status_sync\\.js$': '<rootDir>/js/logic/audit_status_sync.ts',
    '^.+[\\\\/]audit_remote_reload\\.js$': '<rootDir>/js/logic/audit_remote_reload.ts',
    '^.+[\\\\/]prepared_audit_sync\\.js$': '<rootDir>/js/logic/prepared_audit_sync.ts',
    '^.+[\\\\/]audit_remote_push_apply\\.js$': '<rootDir>/js/logic/audit_remote_push_apply.ts',
    '^.+[\\\\/]audit_sync_planning\\.js$': '<rootDir>/js/sync/audit_sync_planning.ts',
    '^.+[\\\\/]audit_sync_execute\\.js$': '<rootDir>/js/sync/audit_sync_execute.ts',
    '^.+[\\\\/]audit_sync_prepare\\.js$': '<rootDir>/js/sync/audit_sync_prepare.ts',
    '^.+[\\\\/]audit_sync_service\\.js$': '<rootDir>/js/sync/audit_sync_service.ts',
    '^.+[\\\\/]audit_sync_unload\\.js$': '<rootDir>/js/sync/audit_sync_unload.ts',
    '^.+[\\\\/]sync_payload_mapper\\.js$': '<rootDir>/js/sync/sync_payload_mapper.ts',
    '^.+[\\\\/]unload_persist_registry\\.js$': '<rootDir>/js/logic/unload_persist_registry.ts',
    '^.+[\\\\/]coerce_audit_for_export\\.js$': '<rootDir>/js/logic/coerce_audit_for_export.ts',
    '^.+[\\\\/]table_pagination_logic\\.js$': '<rootDir>/js/logic/table_pagination_logic.ts',
    '^.+[\\\\/]audit_list_case_grouping\\.js$': '<rootDir>/js/logic/audit_list_case_grouping.ts',
    '^.+[\\\\/]audit_list_group_display_names\\.js$': '<rootDir>/js/logic/audit_list_group_display_names.ts',
    '^.+[\\\\/]audit_list_view_transition\\.js$': '<rootDir>/js/logic/audit_list_view_transition.ts',
    '^.+[\\\\/]expandable_panel_transition\\.js$': '<rootDir>/js/utils/expandable_panel_transition.ts',
    '^.+/translation_logic\\.js$': '<rootDir>/js/translation_logic.ts',
    '^.+/requirement_audit_url_ui\\.js$': '<rootDir>/js/logic/requirement_audit_url_ui.ts',
    '^.+/requirements_list_filters_url_ui\\.js$': '<rootDir>/js/logic/requirements_list_filters_url_ui.ts',
    '^.+/migrate_legacy_query_to_hash\\.js$': '<rootDir>/js/logic/migrate_legacy_query_to_hash.ts',
    '^.+/shareable_app_location\\.js$': '<rootDir>/js/logic/shareable_app_location.ts',
    '^.+[\\\\/]sanitize_media_filename\\.js$': '<rootDir>/shared/media/sanitize_media_filename.ts',
    '^.+[\\\\/]resolve_media_rename_filename\\.js$': '<rootDir>/shared/media/resolve_media_rename_filename.ts',
    '^.+[\\\\/]client_media_validation\\.js$': '<rootDir>/shared/media/client_media_validation.ts',
    '^.+[\\\\/]image_png_upload\\.js$': '<rootDir>/shared/media/image_png_upload.ts',
    '^.+[\\\\/]clipboard_media_files\\.js$': '<rootDir>/shared/media/clipboard_media_files.ts',
    '^.+[\\\\/]media_upload_limits\\.js$': '<rootDir>/shared/constants/media_upload_limits.ts',
    '^.+[\\\\/]browser_online\\.js$': '<rootDir>/js/utils/browser_online.ts',
    '^.+[\\\\/]pending_audit_media_deletes\\.js$': '<rootDir>/js/sync/pending_audit_media_deletes.ts',
    '^.+[\\\\/]attach_media_upload_queue\\.js$': '<rootDir>/js/components/media/attach_media_upload_queue.ts',
    '^.+[\\\\/]attach_media_duplicate_filename_status\\.js$':
      '<rootDir>/js/components/media/attach_media_duplicate_filename_status.ts',
    '^.+[\\\\/]audit_media_api\\.js$': '<rootDir>/js/api/audit_media_api.ts',
    '^.+[\\\\/]audit_granskning_sequence\\.js$': '<rootDir>/js/logic/audit_granskning_sequence.ts',
    '^.+[\\\\/]media_capture_date\\.js$': '<rootDir>/js/logic/media_capture_date.ts',
    '^.+[\\\\/]audit_attached_media_references\\.js$': '<rootDir>/js/logic/audit_attached_media_references.ts',
    '^.+[\\\\/]shared/media/audit_media_filename_migrations\\.js$':
      '<rootDir>/shared/media/audit_media_filename_migrations.ts',
    '^.+[\\\\/]shared/media/resolve_audit_media_server_filename\\.js$':
      '<rootDir>/shared/media/resolve_audit_media_server_filename.ts',
    '^.+[\\\\/]audit_media_server_index\\.js$': '<rootDir>/js/logic/audit_media_server_index.ts',
    '^.+[\\\\/]audit_media_filename_migrations\\.js$': '<rootDir>/js/logic/audit_media_filename_migrations.ts',
    '^.+[\\\\/]audit_media_preview_viewport\\.js$': '<rootDir>/js/logic/audit_media_preview_viewport.ts',
    '^.+[\\\\/]attach_media_file_drop_zone\\.js$': '<rootDir>/js/components/media/attach_media_file_drop_zone.ts',
    '^.+[\\\\/]render_audit_media_list_item\\.js$': '<rootDir>/js/components/media/render_audit_media_list_item.ts',
    '^.+[\\\\/]audit_media_storage\\.js$': '<rootDir>/server/media/audit_media_storage.ts',
    '^.+[\\\\/]audit_grouped_list_render\\.js$': '<rootDir>/js/components/audit_grouped_list_render.ts',
    '^.+[\\\\/]audit_group_row_ui\\.js$': '<rootDir>/js/components/audit_group_row_ui.ts',
    '^.+[\\\\/]audit_group_detail_table\\.js$': '<rootDir>/js/components/audit_group_detail_table.ts',
    '^.+[\\\\/]audit_group_actor_edit_modal\\.js$': '<rootDir>/js/components/audit_group_actor_edit_modal.ts',
    '^.+[\\\\/]AuditGroupedListComponent\\.js$': '<rootDir>/js/components/AuditGroupedListComponent.ts',
    '^.+[\\\\/]attach_media_modal_remove_flow\\.js$': '<rootDir>/js/components/media/attach_media_modal_remove_flow.ts',
    '^.+[\\\\/]attach_media_modal_rename_flow\\.js$': '<rootDir>/js/components/media/attach_media_modal_rename_flow.ts',
    '^.+[\\\\/]attach_media_modal_rename_panel\\.js$': '<rootDir>/js/components/media/attach_media_modal_rename_panel.ts',
    '^.+[\\\\/]attach_media_modal_setup\\.js$': '<rootDir>/js/components/media/attach_media_modal_setup.ts',
    '^.+[\\\\/]attach_media_in_modal_remove_confirm\\.js$':
      '<rootDir>/js/components/media/attach_media_in_modal_remove_confirm.ts',
    '^.+[\\\\/]attach_media_modal_list_focus\\.js$': '<rootDir>/js/components/media/attach_media_modal_list_focus.ts',
    '^.+[\\\\/]attach_media_modal_online_upload\\.js$': '<rootDir>/js/components/media/attach_media_modal_online_upload.ts',
    '^.+[\\\\/]attach_media_modal_persist\\.js$': '<rootDir>/js/components/media/attach_media_modal_persist.ts',
    '^.+[\\\\/]attach_media_modal_list\\.js$': '<rootDir>/js/components/media/attach_media_modal_list.ts',
    '^.+[\\\\/]attach_media_modal_status\\.js$': '<rootDir>/js/components/media/attach_media_modal_status.ts',
    '^.+[\\\\/]attach_media_modal_view_switch\\.js$': '<rootDir>/js/components/media/attach_media_modal_view_switch.ts',
    '^.+[\\\\/]attach_media_in_modal_preview\\.js$': '<rootDir>/js/components/media/attach_media_in_modal_preview.ts',
    '^.+[\\\\/]AttachMediaModal\\.js$': '<rootDir>/js/components/media/AttachMediaModal.ts',
    '^.+[\\\\/]sample_url_auto_screenshot\\.js$': '<rootDir>/js/components/add_sample_form/sample_url_auto_screenshot.ts',
    '^.+[\\\\/]sample_url_auto_screenshot_logic\\.js$':
      '<rootDir>/js/components/add_sample_form/sample_url_auto_screenshot_logic.ts',
    '^.+[\\\\/]sample_attach_media\\.js$': '<rootDir>/js/components/add_sample_form/sample_attach_media.ts',
    '^.+[\\\\/]sample_url_screenshot_form_host\\.js$':
      '<rootDir>/js/components/add_sample_form/sample_url_screenshot_form_host.ts',
    '^.+[\\\\/]sample_url_screenshot_aria_status\\.js$':
      '<rootDir>/js/components/add_sample_form/sample_url_screenshot_aria_status.ts',
    '^.+[\\\\/]sample_url_page_title\\.js$': '<rootDir>/js/components/add_sample_form/sample_url_page_title.ts',
    '^.+[\\\\/]sample_url_page_title_label\\.js$':
      '<rootDir>/js/components/add_sample_form/sample_url_page_title_label.ts',
    '^.+[\\\\/]sample_url_page_title_logic\\.js$':
      '<rootDir>/js/components/add_sample_form/sample_url_page_title_logic.ts',
    '^.+[\\\\/]sample_url_analyze_tasks\\.js$': '<rootDir>/js/components/add_sample_form/sample_url_analyze_tasks.ts',
    '^.+[\\\\/]sample_url_analyze_flow\\.js$': '<rootDir>/js/components/add_sample_form/sample_url_analyze_flow.ts',
    '^.+[\\\\/]sample_url_analyze_progress\\.js$':
      '<rootDir>/js/components/add_sample_form/sample_url_analyze_progress.ts',
    '^.+[\\\\/]sample_url_analyze_task_ui\\.js$':
      '<rootDir>/js/components/add_sample_form/sample_url_analyze_task_ui.ts',
    '^.+[\\\\/]sample_url_analyze_modal\\.js$': '<rootDir>/js/components/add_sample_form/sample_url_analyze_modal.ts',
    '^.+[\\\\/]sample_url_analyze_fetch_snapshot\\.js$':
      '<rootDir>/js/components/add_sample_form/sample_url_analyze_fetch_snapshot.ts',
    '^.+[\\\\/]sample_url_analyze_status\\.js$': '<rootDir>/js/components/add_sample_form/sample_url_analyze_status.ts',
    '^.+[\\\\/]open_audit_media_image_preview\\.js$': '<rootDir>/js/components/media/open_audit_media_image_preview.ts',
    '^.+[\\\\/]audit_media_image_preview_mount\\.js$': '<rootDir>/js/components/media/audit_media_image_preview_mount.ts',
    '^.+[\\\\/]audit_media_preview_observation\\.js$': '<rootDir>/js/components/media/audit_media_preview_observation.ts',
    '^.+[\\\\/]entity_id_match\\.js$': '<rootDir>/js/logic/entity_id_match.ts',
    '^.+[\\\\/]vite_import_meta_hot\\.js$': '<rootDir>/tests/mocks/vite_import_meta_hot.js',
    '^.+[\\\\/]audit_list_last_updated\\.js$': '<rootDir>/js/logic/audit_list_last_updated.ts',
    '^\\./common\\.js$': '<rootDir>/server/schemas/common.ts',
    '^.+[\\\\/]server/schemas/common\\.js$': '<rootDir>/server/schemas/common.ts',
    '^.+[\\\\/]server/schemas/audit_lock\\.js$': '<rootDir>/server/schemas/audit_lock.ts',
    '^.+[\\\\/]server/schemas/audit_create\\.js$': '<rootDir>/server/schemas/audit_create.ts',
    '^.+[\\\\/]server/schemas/audit_patch\\.js$': '<rootDir>/server/schemas/audit_patch.ts',
    '^.+[\\\\/]server/schemas/audit_import\\.js$': '<rootDir>/server/schemas/audit_import.ts',
    '^.+[\\\\/]server/schemas/audit_db_rows\\.js$': '<rootDir>/server/schemas/audit_db_rows.ts',
    '^.+[\\\\/]server/utils/zod_boundary\\.js$': '<rootDir>/server/utils/zod_boundary.ts',
    '^.+[\\\\/]page_screenshot_stealth\\.js$': '<rootDir>/server/services/page_screenshot_stealth.ts',
    '^.+[\\\\/]page_screenshot_lazy_load\\.js$': '<rootDir>/server/services/page_screenshot_lazy_load.ts',
    '^.+[\\\\/]page_screenshot_cookie_consent\\.js$': '<rootDir>/server/services/page_screenshot_cookie_consent.ts',
    '^.+[\\\\/]page_screenshot_cookie_consent_logic\\.js$': '<rootDir>/server/services/page_screenshot_cookie_consent_logic.ts',
    '^.+[\\\\/]page_screenshot_consent_cache_logic\\.js$': '<rootDir>/server/services/page_screenshot_consent_cache_logic.ts',
    '^.+[\\\\/]page_screenshot_consent_cache\\.js$': '<rootDir>/server/services/page_screenshot_consent_cache.ts',
    '^.+[\\\\/]page_screenshot_cmp_block_logic\\.js$': '<rootDir>/server/services/page_screenshot_cmp_block_logic.ts',
    '^.+[\\\\/]page_screenshot_cmp_pattern_families\\.js$': '<rootDir>/server/services/page_screenshot_cmp_pattern_families.ts',
    '^.+[\\\\/]page_screenshot_cmp_block\\.js$': '<rootDir>/server/services/page_screenshot_cmp_block.ts',
    '^.+[\\\\/]page_content_type_detection_rules\\.js$': '<rootDir>/server/services/page_content_type_detection_rules.ts',
    '^.+[\\\\/]page_content_type_detection_service\\.js$': '<rootDir>/server/services/page_content_type_detection_service.ts',
    '^.+[\\\\/]page_screenshot_service\\.js$': '<rootDir>/server/services/page_screenshot_service.ts',
    '^.+[\\\\/]convert_image_to_png\\.js$': '<rootDir>/server/services/convert_image_to_png.ts',
    '^.+[\\\\/]ensure_audit_media_png\\.js$': '<rootDir>/server/services/ensure_audit_media_png.ts',
    '^.+[\\\\/]page_screenshot_capture_height\\.js$': '<rootDir>/server/services/page_screenshot_capture_height.ts',
    '^.+[\\\\/]page_screenshot_browser_scripts_loader\\.js$': '<rootDir>/server/services/page_screenshot_browser_scripts_loader.ts',
    '^.+[\\\\/]pdf_generation_service\\.js$': '<rootDir>/server/services/pdf_generation_service.ts',
    '^.+[\\\\/]pdf_merge_service\\.js$': '<rootDir>/server/services/pdf_merge_service.ts',
  },
  testMatch: [
    '<rootDir>/tests/unit/**/*.spec.js',
    '<rootDir>/tests/unit/**/*.spec.ts',
  ],
  testPathIgnorePatterns: ['/node_modules/', '.e2e.spec.js'],
  /** Tillåt transpilering av marked (ESM) så js/utils/markdown.ts kan laddas i Jest. */
  transformIgnorePatterns: ['/node_modules/(?!(marked)/)'],
  transform: {
    '^.+\\.(t|j)s$': [
      '@swc/jest',
      {
        jsc: {
          parser: {
            syntax: 'typescript',
          },
          target: 'es2022',
        },
        module: {
          type: 'es6',
        },
      },
    ],
  },
  extensionsToTreatAsEsm: ['.ts'],
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  collectCoverageFrom: [
    'js/logic/**/*.{js,ts}',
    'js/api/**/*.{js,ts}',
    'js/state/**/*.{js,ts}',
    '!js/**/*.spec.{js,ts}',
  ],
};
